### PR TITLE
Fix incorrect process metric documentation.

### PR DESCRIPTION
**Pull request by oseiberts11**
Fix an untruth.

Signed-off-by: O Seibert Syseleven <36202147+oseiberts11@users.noreply.github.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
No, I'm pretty sure we expose metrics that summarize the whole unit, aka cgroup.

**Comment by SuperQ** [comment]
Oh, I see, we should probably fix that whole collector to not use PID stats at all. That's totally the wrong thing to export for systemd units.

**Comment by oseiberts11** [comment]
Exactly. There is PR #10 which is supposed to fix this in a better way, but it has been stalled for two years. In the mean time, it has become unmergable. The latest comment "If you're still interested in working on this, please rebase this change against the latest commits." isn't terribly helpful. I gave it a try, but not being familiar with this code base and its other changes in the mean time, I didn't get to the end. There were simply too many merge conflicts.

**Comment by oseiberts11** [comment]
I spent several hours on #66 and after trying it out, it seems it still doesn't actually fix the virtual memory stats that are incorrect here. Or am I missing something?

**Pull request closed without merging**
